# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.23.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.23.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vukmarkovic/CLionProjects/TestingCLion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vukmarkovic/CLionProjects/TestingCLion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.23.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.23.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vukmarkovic/CLionProjects/TestingCLion/CMakeFiles /Users/vukmarkovic/CLionProjects/TestingCLion//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vukmarkovic/CLionProjects/TestingCLion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestingCLion

# Build rule for target.
TestingCLion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestingCLion
.PHONY : TestingCLion

# fast build rule for target.
TestingCLion/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/build
.PHONY : TestingCLion/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/main.cpp.s
.PHONY : main.cpp.s

src/impl/CurlClient.o: src/impl/CurlClient.cpp.o
.PHONY : src/impl/CurlClient.o

# target to build an object file
src/impl/CurlClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/src/impl/CurlClient.cpp.o
.PHONY : src/impl/CurlClient.cpp.o

src/impl/CurlClient.i: src/impl/CurlClient.cpp.i
.PHONY : src/impl/CurlClient.i

# target to preprocess a source file
src/impl/CurlClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/src/impl/CurlClient.cpp.i
.PHONY : src/impl/CurlClient.cpp.i

src/impl/CurlClient.s: src/impl/CurlClient.cpp.s
.PHONY : src/impl/CurlClient.s

# target to generate assembly for a file
src/impl/CurlClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/src/impl/CurlClient.cpp.s
.PHONY : src/impl/CurlClient.cpp.s

src/impl/Request.o: src/impl/Request.cpp.o
.PHONY : src/impl/Request.o

# target to build an object file
src/impl/Request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/src/impl/Request.cpp.o
.PHONY : src/impl/Request.cpp.o

src/impl/Request.i: src/impl/Request.cpp.i
.PHONY : src/impl/Request.i

# target to preprocess a source file
src/impl/Request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/src/impl/Request.cpp.i
.PHONY : src/impl/Request.cpp.i

src/impl/Request.s: src/impl/Request.cpp.s
.PHONY : src/impl/Request.s

# target to generate assembly for a file
src/impl/Request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestingCLion.dir/build.make CMakeFiles/TestingCLion.dir/src/impl/Request.cpp.s
.PHONY : src/impl/Request.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TestingCLion"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/impl/CurlClient.o"
	@echo "... src/impl/CurlClient.i"
	@echo "... src/impl/CurlClient.s"
	@echo "... src/impl/Request.o"
	@echo "... src/impl/Request.i"
	@echo "... src/impl/Request.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

